#!/bin/bash

source common.sh

unset KUBECONFIG

# Explore where Forklift is installed
for localns in $(/usr/bin/oc get forkliftcontrollers.forklift.konveyor.io --all-namespaces --no-headers | awk '{print $1}'); do

  # Collect the Forklift and Kubevirt related CRs
  echo "Gathering Forklift and Kubevirt related CRs for namespaces [${localns}]"
  /usr/bin/gather_crs ${localns} &

  # Collect the logs
  echo "Gathering logs for namespaces [${localns}]"
  /usr/bin/gather_logs ${localns} &

  # Waits for gather_crs, gather_logs, gather_metrics running in background
  echo "Waiting for background gather tasks to finish"
  wait
done

# Tar all must-gather artifacts for faster transmission
# (skipped when MTV_DO_NOT_TAR is set, leaving the plain tree in place)
tar_artifacts


echo "Waiting for copy phase..."
exit 0
